### ISSUE TITLE
Which Font ? 

### ISSUE THREAD

**Issue by notpratheek** [mhinz/dotfiles#2]
Hey @mhinz ! 

This not more of an issue, per se ! But, was just curious as to which font this is, the one you're using in your iTerm (Looks amazing ! 😃 )

![](https://raw.githubusercontent.com/mhinz/dotfiles/master/.github/screenshot-git-light.png)

(also, how did you get the terminal prompt at the bottom ? Is it a Zsh specific thing ? 😅  )

**Comment by mhinz** [comment]
Hi!

Font: Input Mono Regular -> http://input.fontbureau.com

Not sure what you mean about the prompt. :) If I'd clean the screen with `ctrl+l`, the prompt would be at the top again. Nothing special there!

EDIT: I'm closing this now, but feel free to ask further questions in here!
