### ISSUE TITLE
Zsh: Why people are setting default options to their default values?

### ISSUE THREAD

**Issue by kutsan** [mhinz/dotfiles#3]
https://github.com/mhinz/dotfiles/blob/630e4872102b8de0536477df49c4329f5ade5075/.zsh/.zshrc#L29

For example like this line. When I search for it in its man page, it says it's already default. Is there any reason why you are setting it twice? I just don't understand and have seen this in a lot of places.

**Comment by mhinz** [comment]
There's the small chance that default values might change in the future and I like to be explicit about the behaviour I want. :)

**Comment by kutsan** [comment]
Fair point but honestly don't think so. In any case, thank you!
