### ISSUE TITLE
Please explain your cinoptions

### ISSUE THREAD

**Issue by 3N4N** [mhinz/dotfiles#4]
This is not an issue. I've been struggling a lot with c++ indentation in vim. Particularly, this specific case : https://vi.stackexchange.com/questions/15138/set-indentation-when-declaring-constructors-for-c-classes-with-inheritance. I wanted to know what your cinoption does.

**Comment by mhinz** [comment]
I don't know C++.

For me it indents like this:

```cpp
Horse(COLOR color, HANDS height, int age):
  Animal(age),
  itsColor(color),
  itsHeight(height) {
    cout << "Horse constructor...\n";
  } 
```

And this indentation makes sense to me. Whatever the first line means, the items (members?) of the comma-separated list after the colon are indented by one level. And the curly braces open and close on the same level as well.
