### ISSUE TITLE
Sed warning in task finish()

### ISSUE THREAD

**Issue by phcerdan** [mhinz/dotfiles#5]
In https://github.com/mhinz/dotfiles/blob/master/bin/task#L59
```
 line="$(sed -i '' -e "${1}w /dev/stdout" -e "${1}d" ~/tasks)"
```

I was getting warning:  `sed: can't read : No such file or directory`.  The command works though, the task gets deleted.
If I remove the `''` after `-i` the message is gone.
```
 line="$(sed -i -e "${1}w /dev/stdout" -e "${1}d" ~/tasks)"
```

I am using GNU sed 4.5.
Not sure if the `''` was intended. Thanks for your files!

**Comment by mhinz** [comment]
Apparently I never used it on Linux. The `''` is needed for BSD grep (Mac).

It's no critical code, so I simply silence the error now.

Thanks!

> Thanks for your files!

You're welcome!
