### ISSUE TITLE
Theme in screenshot

### ISSUE THREAD

**Issue by domi91c** [mhinz/dotfiles#7]
Hey mhinz,

I really like these dotfiles, and I love the theme you've got displayed in the readme. Could you let me know what that one's called? Also, the light theme displayed in the [Grepper](https://github.com/mhinz/vim-grepper) readme. It's been difficult for me to find light themes that are easy to read. I'd really appreciate it!

**Comment by domi91c** [comment]
Nevermind, it looks like it's Lucius light, with some customizations. Take care!

**Comment by mhinz** [comment]
Exactly. :)
